Part 1 Solutions

In [ ]:
#a) note this could be any values
x = 6
y = 7 
z = 8

print(x+y+z)


21


In [ ]:
#b) 
artists = ['beyonce', 'wizkid', 'burna boy', 'drake', 'rihanna']
print(artists[1])

wizkid


In [ ]:
#b)i)
artists[2] = 'Adele'
print(artists)

['beyonce', 'wizkid', 'Adele', 'drake', 'rihanna']


In [ ]:
#b)ii)
new_artists = ['tems', 'craig david']
artists = artists + new_artists
print(artists)

['beyonce', 'wizkid', 'Adele', 'drake', 'rihanna', 'tems', 'craig david']


In [ ]:
#b)iii)
len(artists)

7

In [ ]:
#c)
my_first_name = 'Anna'

In [ ]:
#d) 
x = 6.7
y = 10
z = True
w = 'Hello World'

In [ ]:
#d)i)
type(x)

float

In [ ]:
#d)ii)
type(y)

int

In [ ]:
#d)iii)
type(z)

bool

In [ ]:
#d)iiii)
type(w)

str

In [ ]:
#e)
employees = {'Sophia': 5000, 'Michael': 2000, 'Lisa': 7000, 'David': 2500}
employees

{'Sophia': 5000, 'Michael': 2000, 'Lisa': 7000, 'David': 2500}

In [ ]:
#e)i)
employees['Sophia'] = 6200
employees

{'Sophia': 6200, 'Michael': 2000, 'Lisa': 7000, 'David': 2500}

In [ ]:
#e)ii)
employees['Emma'] = 8000
employees

{'Sophia': 6200, 'Michael': 2000, 'Lisa': 7000, 'David': 2500, 'Emma': 8000}

In [ ]:
#f)
string1 = 'hello world python is great lovely stuff!'
string1[12:27]

'python is great'

In [ ]:
#g) 
x = 67
y = 5
z = 67.5
w = 10
v = 55

In [ ]:
#g)i)
x > y

True

In [ ]:
#g)ii)
y < v

True

In [ ]:
#g)iii)
w > z

False

In [ ]:
#g) iv)
w > v

False

In [ ]:
#h)
house_price = int(input('How much is the house: '))
deposit = int(input('How much deposit do you want to pay in %: '))
deposit_calc = house_price * (deposit/100)
print(f'The house is is £{house_price}\nYour deposit of {deposit}% means that you need to pay £{deposit_calc}')

How much is the house: 380000
How much deposit do you want to pay in %: 10
The house is is £380000
Your deposit of 10% means that you need to pay £38000.0


In [ ]:
#i)
borrow = int(input('How much would you like to borrow: '))
years = int(input('How many years:'))
months = years * 12
apr = 0.2
total_loan = (borrow * apr) + borrow
total_loan_per_month = total_loan/months

print(f'You would like to borrow £{borrow} over {years} years at an APR% of {apr*100}%\nIn total after {years} years, the total you will pay is £{total_loan}\nThis amounts to £{total_loan_per_month} per month')

How much would you like to borrow: 30000
How many years:10
You would like to borrow £30000 over 10 years at an APR% of 20.0%
In total after 10 years, the total you will pay is £36000.0
This amounts to £300.0 per month


In [ ]:
#j)
countries = 'canada{}usa{}mexico{}australia'
new_countries = countries.split('{}')

In [ ]:
#j) i)
new_countries[2]

'mexico'

Part 2 Solutions

In [ ]:
import numpy as np 

In [ ]:
#a)
x = np.random.randint(5,60,100)

In [ ]:
np.unique(x, return_counts=True)

(array([ 5,  6,  7,  8,  9, 10, 12, 13, 16, 18, 19, 20, 21, 22, 23, 25, 26,
        29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58]),
 array([2, 4, 1, 1, 3, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 3, 2, 1, 3, 1,
        3, 2, 2, 3, 1, 2, 2, 1, 2, 2, 1, 2, 5, 2, 4, 4, 2, 5, 1, 2, 4, 4,
        1, 2]))

In [ ]:
#b)
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
#c)
x = np.random.randint(0,10,(5,5))
x

array([[8, 4, 8, 8, 1],
       [0, 6, 6, 0, 6],
       [6, 5, 8, 7, 8],
       [7, 4, 9, 7, 7],
       [1, 5, 7, 2, 5]])

In [ ]:
#d)
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[10,11,12],[13,14,15]])

In [ ]:
#d)i)
a+b

array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
#d)ii)
a-b

array([[-9, -9, -9],
       [-9, -9, -9]])

In [ ]:
#d)iii)
a*b

array([[10, 22, 36],
       [52, 70, 90]])

In [ ]:
#d)iv)
a/b

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

Part 3 Solutions

In [ ]:
#a)

username = input('What is your username?: ')

if username == 'anna':
  print(f'Welcome {username}, your password is xxxx')
else:
  print('Access denied')

What is your username?: anna
Welcome anna, your password is xxxx


In [ ]:
#b)
random_number = np.random.randint(0,51)
user_guess = int(input('Guess a number between 0 and 50: '))

if random_number == user_guess:
  print('Well done you have guessed correctly!!:)')
else:
  print('Sorry on this occasion, its the wrong guess')

0
Guess a number between 0 and 50: 0
Well done you have guessed correctly!!:)


In [ ]:
200%2

0

In [ ]:
#c) 
user_number = int(input('Give us a number: '))

if user_number % 2 == 0:
  print(f'Your number {user_number} is an even number!')
elif user_number % 2 == 1:
  print(f'Your number {user_number} is an odd number!')
else:
  print('your number is not valid')

Give us a number: 5
Your number 5 is an odd number!


In [ ]:
#d) you could keep adding more permutations to this
player_1 = input('player_1: rock, paper or scissors? ')
player_2 = input('player_2: rock, paper or scissors? ')

if player_1 == 'rock' and player_2 == 'rock':
  print('Thats a tie!!')

if player_1 == 'paper' and player_2 == 'scissors':
  print('player_2 won!')

if player_1 == 'scissors' and player_2 == 'rock':
  print('player_2 won!')

player_1: rock, paper or scissors? scissors
player_2: rock, paper or scissors? rock
player_2 won!
